### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by roggy666** [GeyserMC/Hydraulic#1]
> Configure project :shared
fabric-installer.json not found in dependencies!

> Task :shared:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:compileJava'.
> Could not resolve all dependencies for configuration ':shared:compileClasspath'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/8.1.1/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find :Geyser-Fabric:.
     Searched in the following locations:
       - file:/C:/Users/Glitch/Downloads/Hydraulic/libs/Geyser-Fabric.jar
     Required by:
         project :shared

**Comment by hyphenzero** [comment]
I'm getting the same error.

**Comment by Hiho2950** [comment]
try to remove this as they said cuz they already do it on geyser
    // TODO: Remove this once custom block support
    //       is merged into the master branch. This is
    //       far from ideal, but is the easiest way to
    //       get this working for the time being.
    compileOnly(":Geyser-Fabric")

**Comment by ZoomVA** [comment]
Download https://geysermc.org/download#fabric create a libs folder place the jar in the libs folder and rebuild

**Comment by rtm516** [comment]
Should be resolved with the latest version
