### ISSUE TITLE
Ad Astra render issues

### ISSUE THREAD

**Issue by Elyas2024** [GeyserMC/Hydraulic#12]
im using ad astra on a fabric server, using hydrolic, geyser and floodgate. ad astra rocket and most things with custom model dont render and they take the entier chunk they are on with them.
![Minecraft 4_2_2024 9_24_24 PM](https://github.com/GeyserMC/Hydraulic/assets/159604257/9db60d58-8a46-4caf-ab72-af8846823f3a)

**Comment by rtm516** [comment]
This is a bedrock bug currently. Blocks that are larger than 44 pixels wide cause a content log error and make the chunk (sometimes just subchunk) not render any custom blocks.

Closing in favour of https://github.com/GeyserMC/Hydraulic/issues/11
