### ISSUE TITLE
Hydraulic conflicts with MCXBOX broadcast extension

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [GeyserMC/Hydraulic#2]
Got a server up and can connect  but the items and blocks to register on the bedrock client, but the functionality of blocks and advance items remain. Is there anything else I need to do to add them or is it just not available at the moment.

**Comment by rtm516** [comment]
Modded blocks and items should register automatically, not all will display but most should. Can you provide a log from your modded server?

**Comment by UltraHispeed-Elite** [comment]
Nevermind I got it working now, but I didn't have the fabric api last time that could've been my issue but who knows

**Comment by UltraHispeed-Elite** [comment]
So turns out the blocks and items don't work on Nintendo switch bedrock clients, but do on windows 10 bedrock

**Comment by UltraHispeed-Elite** [comment]
Ok I lied, it's not the switch that's the issue if the MCXboxbroadcast extension that allows me to join on switch that conflicts with Hydraulic

**Comment by rtm516** [comment]
Can you elaborate on your setup more? This seems like it could be a client bug. MCXboxBroadcast doesn't change how the client joins, all it does is point the client at the ip/port configured and its upto the client to connect.

**Comment by UltraHispeed-Elite** [comment]
It was a fabric server with Geyser and floodgate along with biomes o’plenty and it’s library mods, it was working fine with those kids joining through windows 10, but then I added Mcxboxbroadcast extension to join on switch, but when I joined on switch any modded objects didn’t exist on the bedrock client but could still interact with it partial like if there was already a block in the inventory the player could place it but not see it or know. I tried connecting to the server through windows 10 again while the extension was installed and the same issue on the switch was happening on windows so I removed the extension and everything was back on windows 10

**Comment by rtm516** [comment]
Could you try using another method to join on switch? It could just be an issue with that platform

**Comment by UltraHispeed-Elite** [comment]
That's the only method I have of joining of switch available, but even if it was that My windows 10 version of bedrock had the exact same issue when it join the server when the broadcast extension was applied

**Comment by UltraHispeed-Elite** [comment]
![01A0C997-CAA4-425C-BF32-19A744A87897](https://github.com/GeyserMC/Hydraulic/assets/62296749/fefff31a-8bd2-4f3a-bc1c-8143fe372c89)
![6B66AB70-86B6-46D1-A071-C72863FE8435](https://github.com/GeyserMC/Hydraulic/assets/62296749/41227f92-be33-44fb-b6ac-5da29040d296)

**Comment by UltraHispeed-Elite** [comment]
here's a couple of images the one on the top is without the extension and the lower image has the broadcast extension, both are from windows 10

**Comment by rtm516** [comment]
Just tested on my own instance without issue.
