### ISSUE TITLE
crashes the server fabric (1.20.6)

### ISSUE THREAD

**Issue by Smeorkuk** [GeyserMC/Hydraulic#22]
https://mclo.gs/dU147hv        here's the crash
mods:
fabric-api-0.100.8-1.20.6
Floodgate-Fabric-2.2.3-SNAPSHOT+build.25
geyser-fabric-2.3.2-SNAPSHOT+build.697
hydraulic-fabric

**Comment by Smeorkuk** [comment]
works on geyser-fabric-2.3.0-SNAPSHOT+build.592

**Comment by rtm516** [comment]
Duplicate of #20
