### ISSUE TITLE
the mod works right but ...

### ISSUE THREAD

**Issue by moha010209** [GeyserMC/Hydraulic#4]
first bug: is the connected blocks goes in the wrong direction
second bug: blocks when clicking don't show any GUI or inventory or anything like chairs it just teleports me but don't make me sitting down
third bug: that is from the geyser is about movement collision

suggestion: pls add support to use custom skulls without needing to write manually just make Hydraulic handle it by its-self

but about other things are working like converting blocks...etc

**Comment by Redned235** [comment]
As the README says, this project is still highly experimental, so issues are bound to be prevalent in nearly all aspects of the mod. There is still a long way to go and as such, while the project is still in early development, we will not be accepting bug report on more broad issues (I.e. entities don’t work).
